### ISSUE TITLE
Dropdown terminal on wayland always on the same monitor

### ISSUE THREAD

**Issue by stefonarch** [lxqt/qterminal#1142]
We could use `layershell->setScreenConfiguration(LayerShellQt::Window::ScreenConfiguration::ScreenFromCompositor);` to open it where the cursor is, the downside is that it takes a screen resolution/size from one monitor and applies always that.

##### Possible Solution

A menu entry similar to `lxqt-runner`: On wayland open on monitor: active, 1, 2, ?
##### Steps to Reproduce (for bugs)

1. Use dropdown terminal on wayland with a dual head setup with different resolutions.
2. Move cursor between monitors and press shortcut
                                   

##### System Information

* QTerminal version: git

**Comment by tsujan** [comment]
> the downside is that it takes a screen resolution/size from one monitor and applies always that.

Actually, there's an effective workaround for that.

The deeper problem arises when the second (third,...) monitor is scaled. Then the window will have a wrong pixel ratio (= scale factor) inside it, and that will ruin everything. This is a bug in Qt's handling of Wayland — probably in `layer-shell-qt` — and can be seen in lxqt-runner (and other Qt apps) too, although it's tolerable there because lxqt-runner usually has a small window.

**Comment by tsujan** [comment]
A more accurate explanation:

The enum `ScreenFromCompositor` opens the window on the screen with the cursor. So far, so good. However, the window is opened with the pixel ratio it had before.

For example, suppose there are two screens with the same resolution, but the second one has a scale factor of 2. You put the mouse cursor into the first screen and open the dropdown window. Then you close it, put the cursor inside the second screen, and reopen it. Although the pixel ratio of the second screen is 2.0, that of the window is still 1.0. The result is a huge window.

It may be asked, "who scales only one of two monitors that have the same resolution?!" That was only one example; a similar (but a little more complex) situation happens with different resolutions, when only one screen is scaled, or when scale factors are different: we'll end up with a wrong window size — either too big, or too small.

**Comment by tsujan** [comment]
For reference: https://bugs.kde.org/show_bug.cgi?id=482733, https://bugs.kde.org/show_bug.cgi?id=485069, https://bugs.kde.org/show_bug.cgi?id=488780, and probably more.

**Comment by tsujan** [comment]
> On wayland open on monitor: active, 1, 2, ?

The "active" option isn't possible — I explained the reason above.

I made a patch for selecting the monitor under Wayland. It works fine, but I don't think it's a good idea, because the dropdown terminal is still limited to one screen, and changing that screen in Preferences requires an app restart (for the same reason). Hence, not making a PR.

**Comment by tsujan** [comment]
A simple idea is implemented in https://github.com/lxqt/qterminal/pull/1196: If this is impossible by resizing the window, then set the anchors and margins instead, and let the Wayland compositor do the resizing job according to them.
