### ISSUE TITLE
[Feature request] Add icons to "Split terminal" options in the context menu

### ISSUE THREAD

**Issue by uthidata** [lxqt/qterminal#1157]
I'd like to request adding a small icon next to the text that shows the effect of split screen actions in the context menu, the same way there are icons next to copy/paste/zoom... actions.

**Describe the solution you'd like**
Something like [splitscreen_add](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:splitscreen_add:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=split&icon.size=24&icon.color=%235f6368) for horizontal split and [splitscreen_vertical_add](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:splitscreen_vertical_add:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=split&icon.size=24&icon.color=%235f6368) for vertical.

##### Context
I use "Split Terminal Horizontally" and "Split Terminal Vertically" quite often, but recently I've started to forget which one split them side by side and which one split top and bottom. It usually takes me a few tries now, as I picked the wrong one all the time.

**Comment by tsujan** [comment]
It's a good idea. The problem is that we must use icon names that are present in all themes, namely, [Standard Icon Names](https://specifications.freedesktop.org/icon-naming-spec/latest/ar01s04.html).

The only standard icons that may fit are `object-flip-horizontal` and `object-flip-vertical` — _ironically for splitting vertically and horizontally respectively_ — but I'm not sure they're suitable.

**Comment by uthidata** [comment]
In either breeze or oxygen icon theme, you have `view-split-left-right` and `view-split-top-bottom`. Same for some popular icon themes like Papirus and Numix:
https://github.com/search?q=repo%3APapirusDevelopmentTeam%2Fpapirus-icon-theme%20view-split&type=code
https://github.com/search?q=repo%3Avinceliuice%2FWhiteSur-icon-theme+view-split&type=code
https://github.com/search?q=repo%3Anumixproject%2Fnumix-icon-theme+view-split&type=code

Adwaita and Elementary don't have these, but splitting terminals doesn't seem to fit their school of thoughts.

Even if these icons don't exist in the theme, you can still have fallback icons like those in src/icons (otherwise why would those be there?)

If view-split-* and fallback icons can't be used, then maybe the text can be changed to "Split Terminal Left/Right" and "Split Terminal Top/Bottom"? That seems to be how Konsole does it.

**Comment by tsujan** [comment]
> In either breeze or oxygen icon theme, you have

As I said, only standard icon names are acceptable.

**Comment by stefonarch** [comment]
> The only standard icons that may fit are `object-flip-horizontal` and `object-flip-vertical` — _ironically for splitting vertically and horizontally respectively_ — but I'm not sure they're suitable. At least, their Oxygen versions show triangles, which are irrelevant for us.

Papirus's ones are fine, IMO better than nothing.

![immagine](https://github.com/user-attachments/assets/69f16bf2-ea28-4418-8521-08a36bf8b931)

I sue shortcuts to split and even there I make mistakes between Alt+H and Alt+V ...

**Comment by tsujan** [comment]
> Papirus's ones are fine

Apparently, only Oxygen icons corresponding to those standard names are weird, and not in a way that would make them unusable. So, we may want to use them.

**Comment by uthidata** [comment]
> As I said, only standard icon names are acceptable.

How about the text change suggestion? That would not require adding new icons or using flip* icons that are not made for the purpose.

**Comment by tsujan** [comment]
Yes, that's another solution. The current texts aren't user-friendly because the user may expect "horizontally" to mean two views that are horizontally beside each other (I've made that "mistake" too), and the same for "vertically".

Konsole's texts may be the best: "Split View Left-Right" and "Split View Top-Bottom". Any objection?

**Comment by stefonarch** [comment]
Go for it.

**Comment by tsujan** [comment]
Oh, there is a small problem: The mnemonics (underlined shortcuts) are currently "H" and "V". Other mnemonics are all used in menus, especially those for "Top", "Bottom", "Left" and "Right".

So, I suggest using "Horizontal Split Views" and "Vertical Split Views" instead of "Split Terminal Vertically" and "Split Terminal Horizontally" respectively. In that way, "H" and "V" could be kept, although with opposite meanings.

What do you think?

**Comment by stefonarch** [comment]
Hm, that's not much different from now. Mnemnonics will also change in every translation, in italian it's o(rizontal) and v(ertical).

**Comment by uthidata** [comment]
How about "Split Terminal Horizontally (L/R)" then we can keep the mnemonics and not get confused.

**Comment by stefonarch** [comment]
If we don't find any suitable text just the icons will do a lot IMO.

**Comment by tsujan** [comment]
This is what I mean:

![split](https://github.com/user-attachments/assets/180417d1-124e-45fe-a31f-6ea6c63ad7fa)

It's clear and doesn't cause any problem.

> How about "Split Terminal Horizontally (L/R)"

Too long, IMO, and so, not clear enough

>  Horizontal Split View and Vertical Split Views is also hard to translate in some languages 

A translation doesn't need to be made word by word

> If we don't find any suitable text

The current texts are really misleading; they should be changed.

**Comment by tsujan** [comment]
Or they can be "Vertical Subterminals" and "Horizontal Subterminals", like the four other menu-items.

**Comment by tsujan** [comment]
> I think it is not clear what a "vertical" or "horizontal" terminal should be.

It's "Subterminal", not "Terminal", and it's already used in other menu-items. What's not clear about it?!

> BTW the navigation should be greyed out if....

A subject for another report. We also have repeated mnemonics in that menu.

**Comment by uthidata** [comment]
My problem is exactly with the words "vertical" and "horizontal". They are ambiguous. Does "vertical" mean the subterminals are laid out on top of each other, or that the splitter is a vertical line? Hence the wrong clicks.

How about "Split Terminal (stack)" and "Split Terminal (Sideways)"? Idk about mnemonics.

**Comment by tsujan** [comment]
OK. we can go with what we agreed on, namely, "Split View Left-Right" and "Split View Top-Bottom", and we can use "S" and "w" for mnemonics, because those items appear in the context menu too. I'll make a PR.

Translators will have to find appropriate mnemonics that don't clash with the existing ones in the two menus, but that's not a new thing to consider.

Konsole devs "solved" the problem by putting those items inside a sub-menu, but IMO that's not a good solution because it makes them harder to use.

**Comment by stefonarch** [comment]
> > I think it is not clear what a "vertical" or "horizontal" terminal should be.
> 
> It's "Subterminal", not "Terminal",

I ommitted "sub" on purpose. With or without: a terminal can't be "vertical" or "horizonta"l IMO :)
