### ISSUE TITLE
Visual problem when part of a string containing  '⧸' (U+29F8) is selected

### ISSUE THREAD

**Issue by DrinkDregs** [lxqt/qterminal#1186]
[The original report is now invisible to anyone other than me when I'm signed in.]

I've found some other characters that cause the problem:

`ร ว ว เ ส ย ง`

There must be many others.

**Comment by tsujan** [comment]
> [The original report is now invisible to anyone other than me when I'm signed in.]

Thanks for adding it again.

I add your comment in the previous report that mysteriously vanished:

"When selecting a name that contains a /, the whole string moves to the right and a space inserted to the right or left of the selection for every / selected."

I also add my comments in that report :

This may not be an issue in QTerminal, because characters like "U+29F8" contradict the monospace property (= fixed-width).

It happens in Konsole too, but in a worse way.

**Comment by tsujan** [comment]
XTerm cheats but adding a margin after such characters to make them like fixed-width characters, while we use `QPainter::drawText()`, which draws the text as it is, and then the problem arises because the width is smaller than what it should be.

This screenshot shows xterm on the top and QTerminal below it:

![xterm](https://github.com/user-attachments/assets/9e853bd8-619c-49b1-9f7d-2d63bf47d198)

QTerminal (actually, `QPainter::drawText`) draws the text correctly (it's `aabb⧸aabb⧸aabb⧸aabb⧸aabb`), but we don't want that in this case.

A workaround may be to use our own version of `QPainter::drawText()`, but that isn't easy, if possible at all.

**Comment by tsujan** [comment]
Found a simple way of "cheating". It makes QTerminal exactly like XTerm and gnome-terminal in this regard:

![qterminal](https://github.com/user-attachments/assets/3f66cc43-9c31-4ce5-a8a9-0f88c654eb2c)

Will make a PR soon.

**Comment by DrinkDregs** [comment]
The problem resurfaces with this character: `🇬🇧`, which is ceated by combining these two characters: `🇬` `🇧`.

**Comment by tsujan** [comment]
Thanks. Here, most emoji flags are shown as bold, blue character pairs, and some of those that are shown as flags have the problem you described.

That issue is not related to this one, which was about characters whose widths were smaller than monospace. It needs a separate report.
