### ISSUE TITLE
qterminal execution breaks up arguments

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/qterminal#335]
Arguments passed to `qterminal -e` are not properly preserved.
You may compare the behavior to xterm:
```
xterm -e nano "some file with spaces"\ and\ unquoted\ spaces second\ file
qterminal -e nano "some file with spaces"\ and\ unquoted\ spaces second\ file
```
xterm properly sends two arguments to nano, qterminal sends nine.

**Comment by yan12125** [comment]
Yep - ```m_shell``` of ```TerminalConfig``` should use ```QStringList``` instead of ```QString```

**Comment by AlexanderZhirov** [comment]
Wow ... the bug has been hanging since May 27, 2017, it hasn't been fixed yet.

**Comment by tsujan** [comment]
> the bug has been hanging since May 27, 2017, it hasn't been fixed yet.

PRs would be appreciated; tautology wouldn't.

**Comment by AlexanderZhirov** [comment]
So does the problem have a solution or not? Maybe I don't quite understand what to do. The language barrier prevents me from understanding.

**Comment by stefonarch** [comment]
It has sure a solution, but it's not so easy to implement (as @yan12125 wrote).

**Comment by tsujan** [comment]
Please test https://github.com/lxqt/qterminal/pull/961

**Comment by GleammerRay** [comment]
Btw, I know that this is solved in the latest release and all but there's still people sitting with old packages because they aren't getting updated on some distros and I found a very simple way to avoid this problem.

`qterminal -e` has access to all environment variables so just use that.

E.g. `FILE='foo bar' qterminal -e nano '$FILE'` opens `foo bar`.
