### ISSUE TITLE
[FR] Horizontally placed tabs on vertical tab bar

### ISSUE THREAD

**Issue by aramazano** [lxqt/qterminal#410]
Currently tabs are rotated vertically when the tab bar is placed on right or left side of window. 

Even with top/bottom tab bar, there is insufficient space to acommodate more than 5 tabs without overflowing it. And when the tab bar is placed vertically, available scape shrinks even more.

I would suggest keeping tab orientations the same (horizontal) when the tab bar is placed side of the window. This will cause a layout where tabs are stacked up at one side, which should;

1) Allow tens of tabs to be opened without overflowing the -vertical- tab bar,
2) simplify implementation as there will be no need for rotated titles.

Thanks and regards.

**Comment by aramazano** [comment]
PS: Talked about this in https://github.com/lxqt/qterminal/issues/409

**Comment by tsujan** [comment]
Qt doesn't work this way. Tab-bars can be either horizontal or vertical, on the top/bottom or left/right of the page, respectively.

Instead of "horizontal left tabs", for example, Qt has list views, which may be want you want.

I use terminals a lot for developing and other jobs and have never needed a list view in practice, especially when multiple terminals can be opened and there is a drop-down mode too. However, it can be discussed it here.

**Comment by aramazano** [comment]
As long as -from usage point of view- their effects are the same, "horizontally stacked up" tabs or list view are equally OK for me.

And with the new 16x9 LED monitors, vertical tabs make little sense, hence no one uses it. OTOH with a list view I believe it would make good sense and present a use case.

**Comment by aramazano** [comment]
Here is my full system info.

##### System Information
* Distribution & Version: lxqt.debian.net experimental-snapshots on top of Debian Testing (Buster)
* Kernel: 4.9.0-4-amd64
* Qt Version: 5.10.1
* libqtxdg Version: libqt5xdg3 / 3.1.1~13-gb5ddbd4-1
* qtermwidget Version: 0.8.1~24-g4cc05f9-1
* lxqt-build-tools Version: Not installed
* Package version: 0.8.1~36-g1a4452a-1

**Comment by agaida** [comment]
I see no real reason to implement such a feature to be honest.
