### ISSUE TITLE
free(): invalid pointer

### ISSUE THREAD

**Issue by testtube123** [lxqt/qterminal#427]
Whenever I open qterminal I get : free(): invalid pointer 

##### Current Behavior

When I launch qterminal in a new shell it outputs : QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-testube123'
TRANSLATIONS_DIR: Loading translation file "qterminal_en_US.qm" from dir /usr/share/qterminal/translations
load success: false
Properties constructor called
QDir::exists: Empty or null file name
QDir::exists: Empty or null file name
Canot open file "/home/testube123/.config/qterminal.org/qterminal_bookmarks.xml"
default KB_LAYOUT_DIR:  "/usr/share/qtermwidget5/kb-layouts"
loadAllColorSchemes
default KB_LAYOUT_DIR:  "/usr/share/qtermwidget5/kb-layouts"

##### Possible Solution

open new shell either by the file ------> new tab or ctrl-shift-t is the workaround I've found

##### System Information

* Distribution & Version:  Gentoo
* Kernel: 4.17.2-gentoo
* Qt Version: 5
* libqtxdg Version:  
* qtermwidget Version: 5
* lxqt-build-tools Version: unsure
* Package version: 0.71

**Comment by yan12125** [comment]
> Package version: 0.71

I guess you mean 0.7.1? It's severely outdated. Could you try 0.9.0 and see if there's still an issue?

**Comment by jubalh** [comment]
Unfortunately Gentoos LXQt packages are all outdated.

**Comment by agaida** [comment]
@jubalh - not all - it's like in Asterix - some brave people provide current things even for gentoo.

@testtube123 - just use the overlay by @Chiitoo - and please don't tell us anything about stable gentoo packages - we can't and do not care about. If there are any problems, please talk with @Chiitoo

**Comment by Chiitoo** [comment]
I maintain the 'live' packages at this time only, which generally means pulling git master (or any commit via an environment variable).  Usually such packages are only suggested for the adventurous, though I have had only good experiences with LXQt in that regard.  :]

There is effort being put into getting LXQt up-to-date for us on Gentoo (it has been lacking a dedicated maintainer for a time), by me in the past, and a few others after me, but people seem to disappear when they get close... mysteriously.  Well, obviously I didn't, but I digress.

Indeed, please report these things to Gentoo first, especially since the current packages via Portage are out of date (though there really is no need for a duplicate report).  :]

**Comment by jubalh** [comment]
@Chiitoo I maintain some (non LXQt) packages in the Gentoo tree too.

As I understand it there wouldn't be much effort to update the LXQt ebuilds in the official tree based on your work with the 9999 ebuilds, right?

Did you consider syncing your changes over?

**Comment by Chiitoo** [comment]
@jubalh,

I did have a pull request open in the past (https://github.com/gentoo/gentoo/pull/4463), though that was before I made the live packages (which need some improvements still).  There was some more work to be done, and before I got to it, someone else did, but that work never got to the finish line either.

Here's the most recent one, which kind of stalled as well, but is still both open, and a better place for this discussion: https://github.com/gentoo/gentoo/pull/7026

Dessa is currently looking into getting it over the line, and I do believe they'll succeed.  :]

The main difficulty I believe is in having someone actually pick the maintaining duty up, which is not too convenient via proxy-maint due to the amount of packages involved.  While I am a Gentoo developer, I have not (yet?) done the ebuild quizzes, so I don't have the rights to push to the main repository myself.

**Comment by jubalh** [comment]
>Here's the most recent one, which kind of stalled as well, but is still both open, and a better place for this discussion: gentoo/gentoo#7026

Thanks for the link.

> The main difficulty I believe is in having someone actually pick the maintaining duty up, which is not too convenient via proxy-maint due to the amount of packages involved. While I am a Gentoo developer, I have not (yet?) done the ebuild quizzes, so I don't have the rights to push to the main repository myself.

I don't see how this is a lot more work. It's just pushing to a branch instead of master and doing a PR instead of pushing directly.

In any case, I think even with the rights it is good practise to open an PR to have someone review the code :)

**Comment by Chiitoo** [comment]
>I don't see how this is a lot more work. It's just pushing to a branch instead of master and
> doing a PR instead of pushing directly.

Sorry, I didn't mean it that way.  I meant it seems to be difficult to find anyone willing to step up as a maintainer, who does have the rights to push, and usually people are not keen on pushing things to the tree if no one will be maintaining it.  I have considered proxy-maintaining LXQt myself, but have been feeling I wouldn't have the time for it, and stepped to the side when I saw others working on the same goal (I'd help where I could, still).

> In any case, I think even with the rights it is good practise to open an PR to have
> someone review the code :)

Definitely true, depending on the situation a bit.  :]

@testtube123,

I just tested 'x11-terms/qterminal-0.7.1' here, and it seems to work for me, but I'm running with '~amd64' and the 9999 versions for LXQt.  There might be a point in filing a Gentoo bug for this after all (I'll try testing on fully 'amd64' at some point too).
