### ISSUE TITLE
Alt+N shortcut to jump directly to the tab in position N

### ISSUE THREAD

**Issue by robertopierpaoli** [lxqt/qterminal#469]
##### Expected Behavior
Like in LXTerminal, pressing Alt+1 bring the focus to tab 1, Alt+2 to tab 2 and so on.

##### Current Behavior
Currently the Alt-N shortcut is intercepted by bash for passing readling arguments.

##### System Information
* Distribution & Version: Lubuntu 18.04.1 x86_64
* Kernel: 4.15.0-32-generic
* Qt Version: 5.9.5
* libqtxdg Version: none installed 
* qtermwidget Version: 0.8.0
* lxqt-build-tools Version: non installed
* Package version: 0.8.0-4

**Comment by tsujan** [comment]
Very sorry! I though this is opened against pcmanfm-qt! Reopened....

**Comment by robertopierpaoli** [comment]
No worry @tsujan , thank you for the quick feedback!

**Comment by rubyFeedback** [comment]
I was about to open a new issue but I saw this here.

I support the original intent; I would also like to suggest to add some more shortcuts to allow users to use custom keybindings. This behaviour is the only one I am missing from KDE Konsole, the ability to use my own keybindings and use qterminal. It does not affect me that much because I use lxqt as DE and KDE konsole for client stuff, but IF it were possible then I could use qterminal and the keybindings that I have been using for many, many years (it's hard to switch to other keybindings; that is why customization would be really great).

**Comment by yan12125** [comment]
Here is a work-in-progress: https://github.com/lxqt/qterminal/pull/581

@rubyFeedback: I think you can already customize keybindings in Preferences -> Shortcuts?

**Comment by yan12125** [comment]
Now #581 is merged. Thanks @Andersbakken for hard work 👍. To use Alt+N, simply create key bindings in Preferences -> Shortcuts for Go To Tab N actions.

The remaining questiong is: should qterminal use Alt+N for Go To actions by default? A concern is that Alt+N is also used in some terminal applications. For example, readline-based applications (e.g. bash) may use Alt+N to edit arguments [1], and weechat use Alt+N to switch between buffers.

[1] https://stackoverflow.com/a/562179

**Comment by joseSignot** [comment]
The regular ubuntu bash uses alt or ctrl I cant remember? @yan12125

**Comment by yan12125** [comment]
Since last year I have changed my mind. It is likely that default shortcuts conflict with some terminal applications, so I decide to not adding default ones. If someone has some combinations that do not conflict with common terminal applications, please propose them and I will reopen this issue.
