### ISSUE TITLE
No escaping spaces in dropped filenames

### ISSUE THREAD

**Issue by Carmina16** [lxqt/qterminal#474]
If a file is dropped into the terminal which has spaces in its name, it should be quoted. QTerminal doesn't quote it or even escaping spaces.

**Comment by yan12125** [comment]
This function is commented out as it relies on a KDE library kcoreaddons

https://github.com/lxqt/qtermwidget/blob/540c00ffc323846bd7af25b4bf1392dea20c9baa/lib/TerminalDisplay.cpp#L3135

**Comment by agaida** [comment]
Hmm - the question is: Might be kcoreaddons useful for us in other places to - as kcoreaddons are tier1 i would have no big problems to add the dependency.

```
% LANG=C apt show libkf5coreaddons5                     
Package: libkf5coreaddons5
Version: 5.49.0-1
Priority: optional
Section: libs
Source: kcoreaddons
Installed-Size: 691 kB
Depends: libkf5coreaddons-data (= 5.49.0-1), shared-mime-info (>= 1.3), libc6 (>= 2.14), libfam0, libgcc1 (>= 1:3.0), libqt5core5a (>= 5.11.0~rc1), libstdc++6 (>= 4.5)
Download-Size: 208 kB
Description: KDE Frameworks 5 addons to QtCore
 KCoreAddons provides classes built on top of QtCore to perform various tasks
 such as manipulating mime types, autosaving files, creating backup files,
 generating random sequences, performing text manipulations such as macro
 replacement, accessing user information and many more.
 .
 This package is part of KDE Frameworks 5.
```

**Comment by agaida** [comment]
@tsujan @palinek @luis-pereira @yan12125 - if the addons could solve problem and not introduce new ones - why not? I remember that we depend on kcoreaddons times ago, but don't exactly remember why we dropped them.

**Comment by agaida** [comment]
@palinek - i would see it as a feature too

**Comment by tsujan** [comment]
I see it as a good feature. If it can be added relative easily, why not?

**Comment by apjanke** [comment]
> I, personally, don't see the OP as a bug, but a normal behavior. The user has to know if escaping is needed and do escape, what he/she need to escape.

This isn't the case in all terminals. For example, iTerm2 can automatically do escaping of filenames for drag-and-dropped files. And there are zsh or bash add-ons that support quoting or escaping arbitrarily pasted text. The underlying terminal feature used is "bracketed paste mode", which puts a special terminal control sequence before and after pasted text. Then the receiving program (e.g. a shell or text editor) can decide what to do with it, like quoting or escaping it according to their semantics. The terminal knows what text is literal pasted text and needs to be escaped, and the receiving program knows how to do escaping.

Maybe QTerminal could add bracketed paste mode support, and let the shell handle the escaping? It might be hard for QTerminal to do quoting of filenames etc. itself, because it doesn't necessarily know the quoting syntax of the frontmost program running inside the terminal.

**Comment by yan12125** [comment]
I think escaping should be done by the terminal emulator rather than the shell as only the former knows where the string comes from. The string shouldn't be escaped if it's just some plain texts (e.g. dragged-and-dropped from a paragraph on a webpage). As you can see in a linked code segment above, `QMimeData` handles this.

> if the addons could solve problem and not introduce new ones - why not?

Just an implementation note - as KF5 does not work well on macOS due to an Qt bug [1], there should be a CMake option to build qterm* without KF5.

By the way, bracketed paste works fine on Linux. If it doesn't work for you, it might be a macOS-specific issue.

[1] https://bugreports.qt.io/browse/QTBUG-62420

**Comment by probonopd** [comment]
By quoting paths dropped onto QTerminal things would become much smoother.

In 0.15.0 it is broken:

https://user-images.githubusercontent.com/2480569/104396470-033a6980-554b-11eb-892a-e1c4f364f4f3.mp4

Every other terminal application can handle this correctly.

**Comment by probonopd** [comment]
Turns out that the fix is rather straightforward and does not need to introduce new dependencies:

https://user-images.githubusercontent.com/2480569/111673040-da6c7400-881a-11eb-99c9-bb952f82b7ff.mp4

**Comment by probonopd** [comment]
Thank you very much @yan12125
