### ISSUE TITLE
Please add support for sizing of background images

### ISSUE THREAD

**Issue by jasmith79** [lxqt/qterminal#489]
Please add a dropdown that will allow one to e.g. stretch, scale, center, etc. background images. The ability to have them is not terribly useful/pretty if you only see the upper left quadrant of the image without maximizing the terminal window.

**Comment by sethludwig** [comment]
Any update on this?

**Comment by yan12125** [comment]
It is a nice feature and I'd like to see it implemented eventually, but there is no plan in near future as I focus on fixing bugs for now.

**Comment by tsujan** [comment]
I found some time to work on it. Will make 2 PRs for QTermWidget and Qterminal; they shouldn't take long.

**Comment by tsujan** [comment]
Done, after fixing some problems in the code:

![bg](https://user-images.githubusercontent.com/981076/102131040-dbca8100-3e66-11eb-895b-96dfa25a9a29.png)

Blending the background color with the image was a bad idea; the user can choose a translucent image instead. Also, because of a mistake in the code, having a background image was limited to translucent terminals; I fixed that too.

Will make the PRs in one or two days, after more tests.

**Comment by tsujan** [comment]
The PRs are https://github.com/lxqt/qtermwidget/pull/385 and https://github.com/lxqt/qterminal/pull/767 and their patches should be applied in that order.
