### ISSUE TITLE
qterminal crashed, sharing the stacktrace. 

### ISSUE THREAD

**Issue by shirishag75** [lxqt/qterminal#504]
qterminal crashed, attached the stacktrace. 

[coredumpctl-gdb-qterminal.txt](https://github.com/lxqt/qterminal/files/2525807/coredumpctl-gdb-qterminal.txt)

There seem to be missing debug symbols (from the various ?? characters) but need to know which are those and see if the missing packages can be installed. 

```
Package: qterminal
Version: 0.14.0~really~0.9.1~157-gee250b4-1
Severity: normal

-- System Information:
Debian Release: buster/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable-debug'), (500, 'testing-debug'), (500, 'unstable'), (1, 'experimental-debug'), (1, 'experimental')
Architecture: amd64 (x86_64)

Kernel: Linux 4.18.0-2-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages qterminal depends on:
ii  libc6              2.27-6
ii  libqt5core5a       5.11.2+dfsg-3
ii  libqt5dbus5        5.11.2+dfsg-3
ii  libqt5gui5         5.11.2+dfsg-3
ii  libqt5widgets5     5.11.2+dfsg-3
ii  libqt5x11extras5   5.11.2-2
ii  libqtermwidget5-0  0.14.0~really~0.9.1~73-gb17add8-1
ii  libstdc++6         8.2.0-8
ii  libx11-6           2:1.6.7-1

Versions of packages qterminal recommends:
ii  qterminal-l10n  0.14.0~really~0.9.1~157-gee250b4-1

qterminal suggests no packages.

-- no debconf information
```

**Comment by shirishag75** [comment]
I just downloaded and installed libqt5core5a-dbgsym and again ran the same commands, hopefully you will get some more info. 

[coredumpctl-gdb-qterminal.txt](https://github.com/lxqt/qterminal/files/2525835/coredumpctl-gdb-qterminal.txt)

**Comment by tsujan** [comment]
I vaguely remember that Debian had dbg or dbgsym packages but that's @agaida's territory.

**Comment by shirishag75** [comment]
I installed couple of more -dbgsym packages and that adds few more lines but yeah, need @agaida 's input as well I guess. 

[coredumpctl-gdb-qterminal.txt](https://github.com/lxqt/qterminal/files/2525874/coredumpctl-gdb-qterminal.txt)

do you need the /var/lib/systemd/coredump/core.qterminal.1000.277619c20cea4f519bb5447c134bc98f.1458.1540825213000000.lz4 file, maybe that will be helpful ?

**Comment by tsujan** [comment]
The last file is informative. Thanks!

**Comment by shirishag75** [comment]
I am not sure but seems some sort of keyboard combo or something triggers the segmentation fault. I removed all shortcuts which could in anyway close a tab, close window everything but still seems to be triggered by some keyboard combo. Dunno though which as the keyboard has some closely keys. There is possibility that CTRL might be one of the keys but herein would be speculating.

**Comment by tsujan** [comment]
Please see if https://github.com/lxqt/qtermwidget/pull/227 fixes the problem (probably, after there are updates for your qterminal deb packages).

**Comment by shirishag75** [comment]
I would let agaida push it to the .deb package and then will try and tell if the issue remains or gets fixed.

**Comment by agaida** [comment]
@shirishag75 - please use the time until it is uploaded and install systemd-coredump - and activate it if needed - with coredump active everytime a application crashes it will produce a coredump. @tsujan mentioned the debug-symbols. Please install the relevant packages.

Otherwise: Your installation is really messed up - dunno how you managed it to do so - so i would really suggest the siduction iso - there are all needed packages installed to give a good LXQt experience - vbox is sufficient. you migt compare the output `dpkg -l` of your installed system and the output of `dpkg -l `
in vbox. `meld` or `kdiff3` or `kompare` are good tools to do so.

Some notes: Your installation is not a genuine LXQt installation - it was Mate iirc - should be no problem, but some dependencies has alternatives that are used to provide things - that might interfere with LXQt packages. (Example: we recommend pavucontrol-qt | pavucontrol - pavucontrol is installed in your system because of the former installation )

Next thing comes to mind is that i don't know if all of you packages are installed with recommends - it might be surprising, but i really meaned these packages as recommend when i wrote the packages - the only thing is that the applications will not segfault without recommends  - the right way one should read Recommends: is God-damn-these-packages-are-really-recommended-so-install-them-or-be-dead-sure-that-you-very-well-know-why-leave-some-of-them-out: $foo, $bar, $baz :sunglasses:

**Comment by shirishag75** [comment]
I have tried to use recommendations after you shared but I don't know if there is a way to turn on recommendations for all packages. 

And I should have referred to #498 in the bug report so there is some sense from where I got the command.

**Comment by agaida** [comment]
thats easy - take a mini iso and start from scratch - or just tak the siduction iso. Starting from the mini-iso is fun. Boot the image, apt update, apt install task-lxqt-desktop - and be done with. Step two could be: reboot and add the experimental-snapshots, upgrade and restart sddm - ok, right now it is not the right time to do this - running perl transition in unstable.

**Comment by tsujan** [comment]
Although I respect @agaida's opinion, in all years I've had Linux, I did differently: I repaired my system and had *never* had to (re-)install Linux just to repair it -- not a single time.

I even went further when I had Debian: when I got a new laptop, I used CloneZilla to transfer my Debian installation from my Desktop computer to it. And it was completely successful (I just had to install/uninstall some packages).

So, I can't recommend install-to-repair.

**Comment by agaida** [comment]
@tsujan - i'm forced to re-install my systems on a regular base - both things have it's pro and cons. I'm often be surprised how much /etc changes over time - and the very most people don't track this. Next thing in debian world will be the usr-merge thing. Will still leave my workstation as is, but the new installations right now are all with usr-merge - can be a game changer sometimes. So i hereby insist on clean installations as a base for serious bugtracking - and to diff things afterwards if old and new systems don't behave the same. 

Back to topic - we have a policy "problem" in debian - packages with Priority: optional must not conflict - so in some cases some dependencies are fulfilled by "strange" Packages, very hard to track. And it might be that the packaging of some LXQt packages need some improvements (but mostly in the form of recommends) - so it would be nice to now about. But again - very hard to track.

**Comment by tsujan** [comment]
@agaida Believe me: I'm not kind to my system; rolling systems can always be repaired so that they make no difference with a new installations *functionally*. After all, there is a kind of deep satisfaction in doing so. Exciting news for me, 14-15 years ago, was that it was possible with Linux -- it wasn't possible at all with MS Windows.

But that's off topic -- I know.

**Comment by agaida** [comment]
hmm - re:CloneZilla - i prefer a cp -a :P

**Comment by shirishag75** [comment]
tbh, I prefer tjusan's methodology over yours. Starting with scratch in a VM may be possible and for sake of argument let's same those issues are not seen there . It will become harder and not easier to figure out why it's behaving one way or the other. 

There is one other thing as well, I like the fact most linux distributions, at least I can say Debian encourage using multiple desktops, window managers etc. so people can mix and match. if one were to be back to using monolithic, in this case only lxqt-desktop then why shouldn't one go back to MS-Windows. It's good when lxqt-desktop can work with any other GTK/KDE desktop WM etc. That should be a desirious goal, although I know it's also OT here.

**Comment by tsujan** [comment]
> ... It will become harder and not easier to figure out why it's behaving one way or the other.

Exactly! And then, one might have similar problems after (re-)installation and might install it again and have similar problems again and... ;)

2-3 years ago, in Debian forums, people didn't like my idea but it was understandable to me: nowadays, many Linux users come from MS Windows but don't want to change their Windows habits: they still think their systems should be shaky.

> if one were to be back to using monolithic

Never, especially with LXQt.

**Comment by agaida** [comment]
just do what you want to - but i will not spend a minute on frankendebian installations - searching for obscure bugs included.

**Comment by tsujan** [comment]
@agaida Again, I respect your opinion but frankenX is exactly a good chance for finding bugs that can't be seen with an orthodox usage. That's why I have Enlightenment ;) When an app crashes and the backtrace shows where the crash happens, the problem is in the code, not in the installation.

**Comment by agaida** [comment]
Also true :) - but don't forget my remark about recommends, it's important
> the only thing is that the applications will not segfault without recommends - the right way one should read Recommends is: God-damn-these-packages-are-really-recommended-so-install-them-or-be-dead-sure-that-you-very-well-know-why-leave-some-of-them-out: $foo, $bar, $bazthe only thing is that the applications will not segfault without recommends - the right way one should read Recommends is: God-damn-these-packages-are-really-recommended-so-install-them-or-be-dead-sure-that-you-very-well-know-why-leave-some-of-them-out: $foo, $bar, $baz

So a proper installed system (with recommends should work as expected. and there is a problem: if installed the recommend way i'm nearly sure that i don't miss a thing -  but i'm not so sure about if one take a existing installation with $DE and type 

```
apt install qterminal --no-install recommends
```
it's easy to miss something that might be needed that way. As i said, i did not want to debug it, no way - and if a certain lxqt application crash in not reproducible environments i don't care too. So if it is reproducible it might be that the bug is not on our side of the fence. (/me remember the qt5translations thing - so if something is missing what should be there, write a bug against the package and if it is reasonable i will likely change something. I not willing to make the packages idiot proof - that would be against the policy)

**Comment by tsujan** [comment]
> but don't forget my remark about recommends

I completely agree. Not installing Recommends without knowing what they do can have serious consequences.

My point was just that we should welcome any crash+good backtrce, even from a Frankendebian. That was the case for this issue.

**Comment by shirishag75** [comment]
Hi all, 

I tried the following and got the following - 

```
~$  apt install qterminal --no-install recommends 
E: Command line option --no-install is not understood in combination with the other options
```

**Comment by agaida** [comment]
erm, man apt-get
```
OPTIONS
       All command line options may be set using the configuration file, the
       descriptions indicate the configuration option to set. For boolean
       options you can override the config file by using something like
       -f-,--no-f, -f=no or several other variations.

       --no-install-recommends
           Do not consider recommended packages as a dependency for
           installing. Configuration Item: APT::Install-Recommends.
```

**Comment by shirishag75** [comment]
I forgot to share I had tried this though but nothing came - 

```
$ sudo apt-get install qterminal --install-recommends
Reading package lists... Done
Building dependency tree       
Reading state information... Done
qterminal is already the newest version (0.14.0~really~0.9.1~161-g6d374f2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded
```

**Comment by agaida** [comment]
`apt install --reinstall --install-recommends qterminal` would be the way to go - but this don't help if something isn't installed when installing dependencies for qterminal.

**Comment by shirishag75** [comment]
I went through the list of all depends but not depends of depends and everything came out clean, means all the packages for qterminal and its depends are installed with recommends . 

```
$ aptitude show qterminal
Package: qterminal                       
Version: 0.14.0~really~0.9.1~161-g6d374f2-1
State: installed
Automatically installed: no
Priority: optional
Section: x11
Maintainer: LXQt Packaging Team <pkg-lxqt-devel@lists.alioth.debian.org>
Architecture: amd64
Uncompressed Size: 507 k
Depends: libc6 (>= 2.14), libqt5core5a (>= 5.11.0~rc1), libqt5dbus5 (>= 5.0.2),
         libqt5gui5 (>= 5.7.0), libqt5widgets5 (>= 5.11.0~rc1), libqt5x11extras5
         (>= 5.6.0), libqtermwidget5-0 (>= 0.14.0~really~0.9.1~73-gb17add8-1),
         libstdc++6 (>= 5.2), libx11-6
Recommends: qterminal-l10n
Provides: x-terminal-emulator
Description: Lightweight Qt terminal emulator
 QTerminal is a lightweight terminal emulator based on QTermWidget.
```

**Comment by tsujan** [comment]
@shirishag75 I replied to your email. If it isn't received, please check your gmail spam folder (that happens from gmail to gmail too).
