### ISSUE TITLE
Escaping spaces when launching with '-e' option

### ISSUE THREAD

**Issue by wallace11** [lxqt/qterminal#586]
##### Expected Behavior
Properly escape spaces in given paths.

##### Current Behavior
```
$ qterminal -e cd "/path/to/folder name/with/spaces"
...
Shell program: "cd /path/to/folder name/with/spaces"
("cd", "/path/to/folder", "name/with/spaces")
```

##### System Information
* Distribution & Version: Arch Linux x86_64
* Kernel: 5.0.7
* Qt Version: 5.12.2
* qtermwidget Version: 0.14.1
* lxqt-build-tools Version: Unknown. Probably latest...
* Package version: 0.14.1-1

**Comment by yan12125** [comment]
I believe this is the same issue as https://github.com/lxqt/qterminal/issues/335. Unfortunately, the fix appears non-trivial and I haven't had time for a good solution.

**Comment by GleammerRay** [comment]
Btw, I know that this is solved in the latest release and all but there's still people sitting with old packages because they aren't getting updated on some distros and I found a very simple way to avoid this problem.

qterminal -e has access to all environment variables so just use that.

E.g. FILE='foo bar' qterminal -e nano '$FILE' opens foo bar.
