### ISSUE TITLE
Color emoji does not work

### ISSUE THREAD

**Issue by konomikitten** [lxqt/qterminal#626]
##### Expected Behavior
Emoji provided by the noto font should be shown in qterminal.

##### Current Behavior
Only the older monochrome emoji is shown.

![qterminal-xfce-terminal](https://user-images.githubusercontent.com/12713710/64466268-6a286100-d154-11e9-8688-5daa23ad08ec.png)

##### Possible Solution
None.

##### Steps to Reproduce (for bugs)
1. Install the noto font
2. Copy some emoji to your clipboard
3. Paste it into qterminal

##### Context
Not sure what to put here.

##### System Information
* Distribution & Version: Debian GNU/Linux bullseye/sid
* Kernel: Linux debian 5.2.0-2-amd64 #1 SMP Debian 5.2.9-2 (2019-08-21) x86_64 GNU/Linux
* Qt Version: 5.11.3+dfsg1-4
* qtermwidget Version: 0.14.1-1
* lxqt-build-tools Version: 
* Package version:

**Comment by tsujan** [comment]
Why should a terminal emulator show colored emoji?!

**Comment by konomikitten** [comment]
> Why should a terminal emulator show colored emoji?!

Why shouldn't a terminal emulator show colored emoji?

**Comment by tsujan** [comment]
Bad answer!

Terminology (Enlightenment's terminal) plays audio and video files.

**Comment by konomikitten** [comment]
> Terminology (Enlightenment's terminal) plays audio and video files.

Comparing playing audio and video to rendering a font seems like a stretch to me, but okay.

**Comment by kyxcat** [comment]
Just because your use cases for a terminal do not include coloured emojis does not mean that there are no use cases in which coloured emoji support would be irrelevant; such as differentiating certain glyphs which would otherwise be undifferentiatable without this feature, e.g. the coloured square emojis, the coloured circle emojis, the coloured heart emojis. Especially considering the usage of ncurses chat clients, such as weechat, or the use of terminal based mail clients. Personally, this means I won't be using lxqt's terminal, certainly let alone lxqt if the developers are going to hold themselves with this attitude.

**Comment by SoniEx2** [comment]
why not just use a standard font renderer that can actually render fonts? the issue here seems to be that you're just not using a font renderer.

**Comment by tsujan** [comment]
![emoji](https://user-images.githubusercontent.com/981076/64467433-c035de00-d12d-11e9-8ab2-22cf22e9e213.png)

**Comment by agaida** [comment]
bare with my ignorance - but how do i insert emoticons into the terminal :P

**Comment by kyxcat** [comment]
use emojipedia and copy-paste into the terminal, use something that translates shortcodes into the actual emoji, use a character picker such as the emojione picker or something...?

**Comment by agaida** [comment]
ok, i should refine my question:
@tsujan - some integration questions:
* do we have any standard way to define the emoji set systemwide in LXQt?
* do we have an preferred way to use them?

**Comment by tsujan** [comment]
@agaida I'm don't use emoji but to see whether this report was valid or not (it wasn't), I used https://www.compart.com/en/unicode:

Select Noto Color Emoji in FeatherPad or QTerminal or..., go to https://www.google.com/get/noto/help/emoji/, click "View more emoji", paste the code of an emoji into the search-box of https://www.compart.com/en/unicode, select the emoji, paste it by middle clicking.

![fp_emoji](https://user-images.githubusercontent.com/981076/64474341-15eba400-d189-11e9-99fa-82cd530f5a15.png)

**Comment by kyxcat** [comment]
So the answer to both of these questions is that, there is neither a way to select an emoji set systemwide in LXQt, and you're expected to set this specific font for the terminal instead of it having been used as a fallback font for the blocks, nor is there a preferred, integrated way of using them.

It's different to just select the emoji font than it is for it to be chosen as a fallback for the specific emoji blocks. That wasn't the question.

**Comment by kyxcat** [comment]
I don't see how that makes the original question invalid, which is that, people should be able to choose their main font for the actual terminal AND have coloured emojis. :p

**Comment by tsujan** [comment]
@kyxcat You just talk and talk, instead of seeing and listening... The title: "Color emoji does not work". The reality: Color emoji works.

**Comment by kyxcat** [comment]
Colour emoji works... if you select the Noto Colour Emoji font as your terminal font. The point is to have both coloured emoji WITHOUT selecting Noto Colour Emoji as your terminal font. That's how other implementations have it working.

**Comment by konomikitten** [comment]
I could always open another report for qterminal lacking mixed font rendering if that is acceptable?

**Comment by tsujan** [comment]
A clear and correct bug report is always acceptable.

**Comment by cxw42** [comment]
For anyone who found this from Google --- I was able to get color emoji in qterminal 0.14.1 by:
1. following the instructions in https://github.com/lxqt/qterminal/issues/627#issuecomment-529124297 
2. running `fc-cache -rf`
3. opening a new qterminal

![image](https://user-images.githubusercontent.com/10515894/173239940-0d0f872a-eb7f-481b-ab9d-6b79a386a4b8.png)
