### ISSUE TITLE
Undecodable sequence: \001b(hex)[22;0;0t and \001b(hex)]112\0007(hex)

### ISSUE THREAD

**Issue by morfikov** [lxqt/qterminal#640]
I start `qterminal` via the following command:

`qterminal -name 'tmux' -p ~/.config/qterminal-tmux.conf -e "tmux attach-session -t tmux"`

When I close the terminal window, I can see the following messages in the log (the `Undecodable sequence` lines don't appear when I start `qterminal` without tmux):

```
Properties destructor called
Undecodable sequence: \001b(hex)[22;0;0t
Undecodable sequence: \001b(hex)]112\0007(hex)
```

When I then reopen the terminal window (tmux is inside, so the content doesn't disappear), weird things happen.

Sometimes it looks like as if the content of the terminal was cleared -- as you would issue the `clear` command. Most of the time it looks like this:

![2019-10-21-13:01:00](https://user-images.githubusercontent.com/3797768/67200014-e88a4b00-f402-11e9-8fc6-df5bbf336284.png)

The prompts come from closing/reopening the terminal window (+2 for each opening). I didn't have such issue with the previous terminal (rxvt-unicode). So what could be wrong? Is it because of `tmux` or because of the prompt layout, or both?  The time suggests that some command is executed when the window is opened, but there's nothing in the output, like you would just pressed the enter key.

**Comment by yan12125** [comment]
Those warnings are due to missing features in qtermwidget. If you can still run your commands without a problem, those warnings can be ignored. I will create a pull request to disable those warnings.

As a record, `\001b(hex)[22;0;0t` is the command CSI 22 (save window/icon title), and `\001b(hex)]112\0007(hex)` is the command OSC 112 (Reset text cursor color). Those are nice to have features, but I don't really have time to implement them :/
