### ISSUE TITLE
add SaveStateOnExit option

### ISSUE THREAD

**Issue by AvianY** [lxqt/qterminal#642]
Currently, it is annoying to sync `qterminal.ini` file across computers due to the state value changing all the time. Adding a simple option, which would prevent it would be great. 

what do you think?

**Comment by kajukenbo** [comment]
Agreed.

I resized qterminal to 80x24 for testing with vttest & selected the save on exit option
As soon as I UN-selected save on exit (after restarting) the terminal size reverted to a smaller size; something silly like 52x15.

At the very least, I would say the default should be the 80x24 standard.

FWIW, Qterminal 0.14.1 on Debian fails vttest "Test of cursor movements" #2 (the *'s and +'s box test) but seems to pass the rest and seems to pass all  "Test of screen features"
Nice work!

**Comment by uffejakobsen** [comment]
I have the same problem - I'm tracking the .ini file in git - using it across multiple systems

Another possibility was to keep the state in a file separate from the settings

**Comment by correabuscar** [comment]
The problem is, that if you've more than 1 qterminal window open, every window that exits saves its view of the current settings overwriting the settings in the file that you might've set in another window via the Preference(Terminal settings) window.

Say for example you open 2 qterminal windows(not tabs!), then you open Preferences in one and set Application transparency from 0% to 1%, then you apply/ok then you exit/quit/close that window, the settings file now has the 1% setting, but if you now close that other qterminal window(in which you never even touched the settings), bam, back to 0% in the `~/.config/qterminal.org/qterminal.ini` file, and thus whatever you set previously got lost.

qterminal 2.0.1

**Comment by stefonarch** [comment]
Yeah, this can be quite tricky when configuring qterminal dropdown and another window is open.

**Comment by tsujan** [comment]
Synchronization of settings can be done through D-Bus. It needs some deep  — but not necessarily heavy — changes to the code. I'll look into it if I find the time.

Is there an open issue about it?

**Comment by tsujan** [comment]
Some settings are saved to disk when the Apply button of settings dialog is clicked; some others when the app exits. This code structure is crucial for saving the correct settings when only one instance is running, but it'll cause confusion if settings are changed while more than one instance is running.

If the app had only one instance, no problem would happen *in this regard* because all settings would be synchronized automatically. But, as I've mentioned in other places, it isn't wise to make QTerminal be a single-instance app (a crash in one window would crash all others, and that would be very bad for a terminal emulator).

Watching the config file (as alacritty does) is a solution; Qt can do it easily. Personally, I think file watching is a "harsh" thing to do and should be done only if necessary, but there may be no better solution.

**Comment by UffeJakobsen** [comment]
Just a little note: _please_ do _not_ make QTerminal into a single-instance application - I would hate that...

**Comment by tsujan** [comment]
> I would hate that...

And I'm against it ;) It isn't safe.

Please open a separate issue about the problems of changing the settings with more than one instance running. This page isn't an appropriate place for discussing it.

**Comment by stefonarch** [comment]
Issue is opened here: https://github.com/lxqt/qterminal/issues/1145

**Comment by tsujan** [comment]
→ https://github.com/lxqt/qterminal/commit/78755a23f00e87bd8f126e56492a76127c21f71b
