### ISSUE TITLE
Incorrectly rendered ligatures with Fira Code

### ISSUE THREAD

**Issue by nilp0inter** [lxqt/qterminal#684]
##### Expected Behavior

Long ligatures should render properly. As an example, this is the expected behavior when rendering an ASCII progress bar with Fira Code.

![image](https://user-images.githubusercontent.com/1224006/83681013-10b96980-a5e2-11ea-8c02-a32f0d8e172d.png)

##### Current Behavior

Currently QTerminal (and Konsole) render it wrong.

![image](https://user-images.githubusercontent.com/1224006/83681075-262e9380-a5e2-11ea-8e84-d9cc92e7916c.png)

##### Steps to Reproduce (for bugs)

1. Install Fira Code (https://github.com/tonsky/FiraCode)
2. Set Fira Code as the default font in QTerminal
3. Run `echo '4ce9f247a3c6: Loading layer [==================================================>]  49.66MB/49.66MB'`

##### Context

This bugs makes progress bars and long ligature glyphs render very badly (specially on programs that use them for dynamically display information).

##### System Information

* Distribution & Version: Arch
* Kernel: 5.6.15-arch1-1
* Qt Version: 5.14.2
* qtermwidget Version: ???
* lxqt-build-tools Version: ???
* Package version: 0.15.0

##### Additional notes

- This bug also affects Konsole, so maybe is a Qt bug?
- I've reported it here https://bugs.kde.org/show_bug.cgi?id=422431
- You can see here the [original issue](https://github.com/tonsky/FiraCode/issues/1064) (in the Fira Code repo)

**Comment by tsujan** [comment]
> This bug also affects Konsole, so maybe is a Qt bug?

Or, maybe, a bug in Fira Code. If it works fine in all non-Qt terminal emulators, that doesn't show the bug is in Qt or Konsole or QTerminal. For example, I remember a "monospace" font (but don't remember its name) which was *correctly* detected as non-monospace by Qt but not by GTK (or its specialized libraries).

**Comment by tsujan** [comment]
In addition, I can type "continuous progressbars" with DejaVu Sans Mono and appropriate characters in Qterminal:


![progressbar](https://user-images.githubusercontent.com/981076/83688943-6fdba600-a603-11ea-82d3-8354f6e86623.png)

**Comment by nilp0inter** [comment]
Any idea on how we can debug and identify where the bug is? I am pretty new to ligatures.

**Comment by tsujan** [comment]
> I am pretty new to ligatures.

Then you know more than I do ;) I just played with characters:

![example](https://user-images.githubusercontent.com/981076/83698219-2052a580-a616-11ea-8b2b-87a92b457496.png)

[example.txt](https://github.com/lxqt/qterminal/files/4726643/example.txt)

**Comment by tsujan** [comment]
This shows how reliable Qterminal's rendering is (but doesn't disprove your report):

![madness](https://user-images.githubusercontent.com/981076/83699999-d5875c80-a61a-11ea-89b0-dea270da3bf1.png)

Taken from http://xahlee.info/comp/unicode_drawing_shapes.html

**Comment by yan12125** [comment]
I installed Fira Code from the Arch Linux official package [1], and make qterminal to use that by modifying `~/.config/qterminal.org/qterminal.ini` (somehow Fira Code is not considered a mono-spaced font by Qt)

```
fontFamily=Fira Code
```

And the original example works fine

![image](https://user-images.githubusercontent.com/1937689/90329606-e409d100-dfd8-11ea-94b2-c4bb86a73bb1.png)

Combining other examples provided by @tsujan, I consider your issue is from somewhere other than qterminal. I'm sorry I cannot help on debugging as I'm not familiar with ligatures. You may get better help from Arch Linux forums.

If in the end you find out the issue is indeed from qterminal, feel free to leave a comment here and I will reopen the issue.

[1] https://www.archlinux.org/packages/community/any/ttf-fira-code/

**Comment by nilp0inter** [comment]
Thank you @yan12125 , that info is very helpful.
