### ISSUE TITLE
qterminal 0.14.1 have so many bugs how long it will take to make 0.15.0 available in package managers like apt?

### ISSUE THREAD

**Issue by jattboe** [lxqt/qterminal#705]
- **0.15.0** is released in **April** and even after **5 months** not available in package managers like **apt**.
- So many issues in **0.14.1** and most of them are fixed in **0.15.0**.
- How long it will take to make this version available in package managers like **apt**?

**Comment by tsujan** [comment]
These are downstream questions, which you may want to ask of the maintainers of your distro (Debian, Ubuntu,...?).

**Comment by jubalh** [comment]
@jattboe this does have **nothing** to do with us. It is not in our control.
It depends on the policy of the distribution and the activeness of the maintainer.
AFAIK we don't have an active Debian maintainer right now (right?), so that will be a problem.

openSUSE, Arch, Fedora Rawhide and many more have qterminal 0.15 since a long time as you can see here: https://repology.org/project/qterminal/versions

So when deciding on which distributio to use one should really inform oneself about their activity and guidelines.
