### ISSUE TITLE
Improve interaction between dropdown and fullscreen

### ISSUE THREAD

**Issue by AKSoo** [lxqt/qterminal#921]
##### Expected Behavior
* Activating fullscreen (default F11) should make a dropdown terminal fill the screen immediately.
* Pressing the shortcut should return the terminal to the user's dropdown width/height.

##### Current Behavior
* After activating fullscreen, you need to close and reopen the dropdown to make it fill the screen.
* Deactivating a fullscreen dropdown returns the terminal to the last saved **window** sizes, not the dropdown width/height.

##### Context
Would allow users to go in and out of fullscreen from dropdown

##### System Information
* QTerminal version: 1.0.0-1
* Distribution & Version: Arch Linux
* Kernel: Linux 5.15.26-1-lts
* Qt Version: 5.15.3+kde+r132-1

**Comment by tsujan** [comment]
> Activating fullscreen (default F11) should make a dropdown terminal fill the screen immediately.

It does, with the latest git.

> Pressing the shortcut should return the terminal to the user's dropdown width/height.

If by shortcut you mean fullscreen shortcut, it does, with latest git.

Recently, the master branch received a commit that fixed several issues in the drop-down mode. Of course, it doesn't exist in 1.0.0.

However, I don't close this report because I found a minor issue in using the fullscreen shortcut with the drop-down mode. It isn't mentioned in the report but I'll explain (and probably, fix) it later if I find the time.

**Comment by tsujan** [comment]
I've described the issue in the PR's comment: https://github.com/lxqt/qterminal/pull/922
